# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
changelog:
  skip: true
builds:
  - binary: tweety
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE-MIT
release:
  prerelease: auto
  extra_files:
    - glob: config.schema.json
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: tweety
    homepage: https://pomdtr.github.io/tweety
    service: |
      run [ opt_bin/"tweety" ]
      keep_alive true
      working_dir HOMEBREW_PREFIX
      log_path var/"log/tweety.log"
      error_log_path var/"log/tweety.log"
    repository:
      owner: pomdtr
      name: homebrew-tap
    install: |-
      bin.install "tweety"
