# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - sh -c 'go run ./cmd/popcorn completion "bash" >./completions/{{ .ProjectName }}.bash'
    - sh -c 'go run ./cmd/popcorn completion "zsh" >./completions/{{ .ProjectName }}.zsh'
    - sh -c 'go run ./cmd/popcorn completion "fish" >./completions/{{ .ProjectName }}.fish'
changelog:
  skip: true
builds:
  - binary: popcorn
    main: ./cmd/devbox/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE-MIT
      - completions/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: popcorn
    homepage: https://pomdtr.github.io/popcorn
    repository:
      owner: pomdtr
      name: homebrew-tap
    install: |-
      bin.install "popcorn"
      bash_completion.install "completions/popcorn.bash"
      zsh_completion.install "completions/popcorn.zsh"
      fish_completion.install "completions/popcorn.fish"
