# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - sh -c 'go run ./cmd/tweety completion "bash" >./completions/{{ .ProjectName }}.bash'
    - sh -c 'go run ./cmd/tweety completion "zsh" >./completions/{{ .ProjectName }}.zsh'
    - sh -c 'go run ./cmd/tweety completion "fish" >./completions/{{ .ProjectName }}.fish'
changelog:
  skip: true
builds:
  - binary: tweety
    main: ./cmd/tweety/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE-MIT
      - completions/*
release:
  prerelease: auto
  extra_files:
    - glob: config.schema.json
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: tweety
    homepage: https://pomdtr.github.io/tweety
    repository:
      owner: pomdtr
      name: homebrew-tap
    install: |-
      bin.install "tweety"
      bash_completion.install "completions/tweety.bash"
      zsh_completion.install "completions/tweety.zsh"
      fish_completion.install "completions/tweety.fish"
