version: "3"

tasks:
  build-frontend:
    desc: Build the frontend
    cmds:
      - npm run build
    dir: frontend

  build:
    deps: [build-frontend]
    desc: Compile the Go binary
    cmds:
      - go build -o bin/tweety .

  install:
    deps: [build-frontend]
    desc: Install the Go binary
    cmds:
      - go install
